\version "2.19.82"
\language "english"

\header {
    tagline = ##f
}

\layout {}

\paper {}

\score {
    \new StaffGroup
    <<
        \new RhythmicStaff
        \with
        {
            \consists Horizontal_bracket_engraver
        }
        {
            {
                \clef "percussion"
                r4
                c'4
                r4
                r8
                [
                c'8
                ]
                r4
                c'4
                r4
                c'4
                r4
                c'4
                r4
                r8
                [
                c'8
                ]
                r4
                c'16
                [
                c'16
                r8
                ]
                c'16
                [
                c'16
                r8
                ]
                r8
                [
                c'8
                ]
                r4
                c'4
                r4
                r8
                [
                c'8
                ]
                r4
                c'4
                r4
                c'4
                r4
                c'4
                r4
                r8
                [
                c'8
                ]
                r4
                c'16
                [
                c'16
                r8
                ]
                c'16
                [
                c'16
                r8
                ]
                r8
                [
                c'8
                ]
                r4
                c'4
                r4
                r8
                [
                c'8
                ]
                r4
                c'4
                r4
                c'4
                r4
                c'4
                r4
                r8
                [
                c'8
                ]
                r4
                c'16
                [
                c'16
                r8
                ]
                c'16
                [
                c'16
                r8
                ]
                r8
                [
                c'8
                ]
                r4
                c'4
                r4
                r8
                [
                c'8
                ]
                r4
                c'4
                r4
                c'4
                r4
                c'4
                r4
                r8
                [
                c'8
                ]
                r4
                c'16
                [
                c'16
                r8
                ]
                c'16
                [
                c'16
                r8
                ]
                r8
                [
                c'8
                ]
            }
        }
        \new RhythmicStaff
        \with
        {
            \consists Horizontal_bracket_engraver
        }
        {
            {
                \clef "percussion"
                c'4
                c'4
                c'8
                [
                c'8
                ]
                c'4
                c'4
                c'4
                c'4
                c'4
                c'4
                c'4
                c'8
                [
                c'8
                ]
                c'4
                c'4
                c'8
                [
                c'8
                ]
                r2
                c'4
                c'4
                c'8
                [
                c'8
                ]
                c'4
                c'4
                c'4
                c'4
                c'4
                c'4
                c'4
                c'8
                [
                c'8
                ]
                c'4
                c'4
                c'8
                [
                c'8
                ]
                r2
                c'4
                c'4
                c'8
                [
                c'8
                ]
                c'4
                c'4
                c'4
                c'4
                c'4
                c'4
                c'4
                c'8
                [
                c'8
                ]
                c'4
                c'4
                c'8
                [
                c'8
                ]
                r2
                c'4
                c'4
                c'8
                [
                c'8
                ]
                c'4
                c'4
                c'4
                c'4
                c'4
                c'4
                c'4
                c'8
                [
                c'8
                ]
                c'4
                c'4
                c'8
                [
                c'8
                ]
                r2
            }
        }
    >>
    \midi {}
}