\version "2.19.82"
\language "english"

\header {
    tagline = ##f
}

\layout {}

\paper {}

\score {
    <<
        {
            d'8
            [
            e'8
            ]
            f'8
            [
            a'8
            ]
            e'8
            [
            f'8
            ]
            a'8
            [
            b'8
            ]
            f'8
            [
            a'8
            ]
            b'8
            [
            c''8
            ]
            b'8
            [
            a'8
            ]
            f'8
            [
            e'8
            ]
            d'8
            [
            e'8
            ]
            f'8
            [
            a'8
            ]
            e'8
            [
            f'8
            ]
            a'8
            [
            b'8
            ]
            f'8
            [
            a'8
            ]
            b'8
            [
            c''8
            ]
            b'8
            [
            a'8
            ]
            f'8
            [
            e'8
            ]
            d'8
            [
            e'8
            ]
            f'8
            [
            a'8
            ]
            e'8
            [
            f'8
            ]
            a'8
            [
            b'8
            ]
            f'8
            [
            a'8
            ]
            b'8
            [
            c''8
            ]
            b'8
            [
            a'8
            ]
            f'8
            [
            e'8
            ]
            d'8
            [
            e'8
            ]
            f'8
            [
            a'8
            ]
            e'8
            [
            f'8
            ]
            a'8
            [
            b'8
            ]
            f'8
            [
            a'8
            ]
            b'8
            [
            c''8
            ]
            b'8
            [
            a'8
            ]
            f'8
            [
            e'8
            ]
        }
        {
            g'8
            [
            a'8
            ]
            bf'8
            [
            d''8
            ]
            a'8
            [
            bf'8
            ]
            d''8
            [
            e''8
            ]
            bf'8
            [
            d''8
            ]
            e''8
            [
            f''8
            ]
            e''8
            [
            d''8
            ]
            bf'8
            [
            a'8
            ]
            g'8
            [
            a'8
            ]
            bf'8
            [
            d''8
            ]
            a'8
            [
            bf'8
            ]
            d''8
            [
            e''8
            ]
            bf'8
            [
            d''8
            ]
            e''8
            [
            f''8
            ]
            e''8
            [
            d''8
            ]
            bf'8
            [
            a'8
            ]
            g'8
            [
            a'8
            ]
            bf'8
            [
            d''8
            ]
            a'8
            [
            bf'8
            ]
            d''8
            [
            e''8
            ]
            bf'8
            [
            d''8
            ]
            e''8
            [
            f''8
            ]
            e''8
            [
            d''8
            ]
            bf'8
            [
            a'8
            ]
            g'8
            [
            a'8
            ]
            bf'8
            [
            d''8
            ]
            a'8
            [
            bf'8
            ]
            d''8
            [
            e''8
            ]
            bf'8
            [
            d''8
            ]
            e''8
            [
            f''8
            ]
            e''8
            [
            d''8
            ]
            bf'8
            [
            a'8
            ]
        }
    >>
}