\version "2.19.82"
\language "english"

\include "/Users/rwest/Code/mirrorecho/rwestmusic-imaginary/imaginary/scores/stylesheets/parts.ily"

\header {
    tagline = ##f
}

\layout {}

\paper {}

\score {
    \context Score = "guitar"
    <<
        \context Staff = "guitar"
        \with
        {
            \consists Horizontal_bracket_engraver
        }
        {
            {
                \tempo "SECTION A" 4=110
                \accidentalStyle modern-cautionary
                \set Staff.instrumentName = \markup { Guitar }
                \set Staff.shortInstrumentName = \markup { Gtr. }
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
                d'8
                [
                e'8
                ]
                a'8
                [
                b'8
                ]
                c'8
                [
                e'8
                ]
                a'8
                [
                f'8
                ]
                c''8
                [
                a'8
                ]
                b'8
                [
                c''8
                ]
                d''8
                [
                b'8
                ]
                g'8
                [
                e'8
                ]
            }
        }
    >>
}